# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
